
    create table public.days_of_week (
       day_of_week_id integer generated by default as identity,
        day varchar(255) not null,
        primary key (day_of_week_id)
    )

    create table public.episode (
       episode_id integer not null,
        airtdate date,
        airtime time,
        image varchar(255),
        name varchar(255),
        number integer,
        runtime integer,
        summary varchar(255),
        tvmaze_url varchar(255),
        season_id integer,
        primary key (episode_id)
    )


        create table public.season (
       season_id integer not null,
        end_date date not null,
        episode_order integer not null,
        image_url varchar(255) not null,
        number integer not null,
        premiere_date date not null,
        summary varchar(5000) not null,
        tvmaze_url varchar(255) not null,
        show_id integer,
        primary key (season_id)
    )


    alter table public.episode
       add constraint FKr5ifuxa82mfaxrhgahps7iu2m
       foreign key (season_id)
       references public.season
    alter table public.season
       add constraint FKp8b7jfne6nim2mjk87rkw7ksf
       foreign key (show_id)
       references public.show

    create table public.genre (
       genre_id integer generated by default as identity,
        genre varchar(255) not null,
        primary key (genre_id)
    )

    create table public.schedule (
       schedule_id integer generated by default as identity,
        time_of_show time,
        primary key (schedule_id)
    )

    create table public.schedule_days_of_week (
       schedule_id integer not null,
        days_of_week_id integer not null,
        primary key (schedule_id, days_of_week_id)
    )



    create table public.show (
       show_id integer not null,
        image_url varchar(255) not null,
        imdb_url varchar(255) not null,
        language varchar(255) not null,
        name varchar(255) not null,
        offical_site_url varchar(255) not null,
        premiered date not null,
        runtime integer not null,
        status varchar(255) not null,
        summary varchar(5000) not null,
        tv_maze_url varchar(255) not null,
        type varchar(255) not null,
        schedule_id integer not null,
        primary key (show_id)
    )

    create table public.show_genre (
       show_id integer not null,
        genre_id integer not null
    )

    alter table public.days_of_week 
       add constraint UK_bxhnmmykhnfn7urbrg8k2pxrh unique (day)

    alter table public.genre 
       add constraint UK_89b48lwadspmkos0rx7hidlty unique (genre)

    alter table public.show 
       add constraint UK_9cxledwc4ri5fqjxg620jf6n6 unique (schedule_id)


    alter table public.schedule_days_of_week
       add constraint fk_schedule_days_of_week_days_of_week
       foreign key (days_of_week_id)
       references public.days_of_week

    alter table public.schedule_days_of_week
       add constraint fk_schedule_days_of_week_schedule
       foreign key (schedule_id)
       references public.schedule

    alter table public.episode
       add constraint FKr5ifuxa82mfaxrhgahps7iu2m 
       foreign key (season_id) 
       references public.season
    alter table public.season
       add constraint FKp8b7jfne6nim2mjk87rkw7ksf 
       foreign key (show_id) 
       references public.show

    alter table public.show 
       add constraint fk_show_schedule_id 
       foreign key (schedule_id) 
       references public.schedule

    alter table public.show_genre 
       add constraint fk_show_genre_show 
       foreign key (genre_id) 
       references public.genre

    alter table public.show_genre 
       add constraint fk_show_genre_genre 
       foreign key (show_id) 
       references public.show
